[build]
  base = "frontend/"
  publish = "dist/"
  command = "pnpm install && pnpm run build"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "pnpm run dev"
  port = 5173
  publish = "dist/"

